prometheus:
  image: prom/prometheus:latest
  container_name: monitoring_prometheus
  restart: unless-stopped
  volumes:
    - ~/monitor/prometheus/config:/etc/prometheus
    - ~/monitor/prometheus/data:/var/lib/prometheus
  command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/var/lib/prometheus'
  expose:
    - 9090
  ports:
    - 9090:9090
  links:
    - cadvisor:cadvisor
    - node-exporter:node-exporter

node-exporter:
  image: prom/node-exporter:latest
  container_name: monitoring_node_exporter
  restart: unless-stopped
  expose:
    - 9100

cadvisor:
  image: google/cadvisor:latest
  container_name: monitoring_cadvisor
  restart: unless-stopped
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  expose:
    - 8080

grafana:
  image: grafana/grafana:latest
  container_name: monitoring_grafana
  restart: unless-stopped
  expose:
    - 3000
  ports:
    - 3000:3000
  links:
    - prometheus:prometheus
  volumes:
    - ~/monitor/grafana:/var/lib/grafana
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=centling
    - GF_USERS_ALLOW_SIGN_UP=false
    - GF_SERVER_DOMAIN=myrul.com
    - GF_SMTP_ENABLED=true
    - GF_SMTP_HOST=smtp.gmail.com:587
    - GF_SMTP_USER=myadrress@gmail.com
    - GF_SMTP_PASSWORD=mypassword
    - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
